#! /bin/sh

# Start sxhkd if not already running
pgrep -x sxhkd > /dev/null || sxhkd &

# Define desktops
bspc monitor -d I II III IV V

# Set initail window layout
bspc config border_width		2
bspc config window_gap			10
bspc config split_ratio			0.5
bspc config focused_border_color	"#5E81AC"
bspc config normal_border_color		"#4C566A"

# Ensure layout is tiled
bspc config automatic_scheme longest_side
bspc config initial_polarity first_child
bspc config removal_adjustment true

# Set Wallpaper
feh --bg-fill ~/Pictures/wallpapers/noctyra.png &

# Launch Polybar before terminal
~/.config/polybar/launch.sh & 

# Launch terminal
kitty &
