#! /bin/sh

# Start sxhkd if not already running
pgrep -x sxhkd > /dev/null || sxhkd &

# Define desktops
bspc monitor -d I II III IV V

# Set initail window layout
bspc config border_width		2
bspc config window_gap			10
bspc config split_ratio			0.5
bspc config focused_border_color	"$(cat ~/.cache/wal/colors | sed -n '3p')"
bspc config normal_border_color		"$(cat ~/.cache/wal/colors | sed -n '1p')"

# Ensure layout is tiled
bspc config automatic_scheme longest_side
bspc config initial_polarity first_child
bspc config removal_adjustment true

# Set Wallpaper
feh --bg-fill ~/Pictures/wallpapers/wallpaper.jpg &

# Gernerate color theme
wal -i ~/Pictures/wallpapers/wallpaper.jpg &

# Picom
picom --config ~/.config/picom/picom.conf &

# Launch Polybar
~/.config/polybar/launch.sh &

# Clipbard Manager
diodon &

# Launch terminal
kitty &
